lsi: false
safe: true
baseurl: /PROJECT
url: http://ldalton02.github.io/self-site/
root: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge